
$mainMod = SUPER
# Sink volume raise optionally with --device
bind= ,XF86AudioRaiseVolume, exec, volumectl -u up
# Sink volume lower optionally with --device
bind =  ,XF86AudioLowerVolume ,exec  ,volumectl -u down
# Sink volume toggle mute
bind = ,XF86AudioMute ,exec ,volumectl toggle-mute

# Brightness raise
bind = ,XF86MonBrightnessUp ,exec , lightctl up
# Brightness lower
bind = ,XF86MonBrightnessDown ,exec , lightctl down

bind = ,XF86AudioPrev, exec, playerctl previous 
bindl = , xf86audioplay, exec, playerctl play-pause
bind = ,XF86AudioNext, exec, playerctl next

bind = $mainMod CTRL, bracketleft, movetoworkspace, -1
bind = $mainMod CTRL, bracketright, movetoworkspace, +1

bind = $mainMod SHIFT, bracketright, workspace, +1
bind = $mainMod SHIFT, bracketleft, workspace, -1

bind = $mainMod CTRL, left, swapwindow, l
bind = $mainMod CTRL, right, swapwindow, r
bind = $mainMod CTRL, up, swapwindow, u
bind = $mainMod CTRL, down, swapwindow, d

bind = $mainMod, K, exec, ~/.config/hypr/hyprland-layoutswitch/keyboardswitch.sh

bind = CTRL ALT, delete, exec, nwg-bar 
