#+title: Doom literate config

* File Headline
#+begin_src emacs-lisp :tangle yes
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src
* User informations
#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Frédéric Willem"
      user-mail-address "frederic.willem@gmail.com")
#+end_src
* Calendar/holidays
#+begin_src emacs-lisp :tangle yes
(setq calendar-location-name "Saint-Nicolas, BE"
      calendar-latitude 50.628
      calendar-longitude 5.516)
(custom-set-variables
 '(holiday-bahai-holidays nil)
 '(holiday-hebrew-holidays nil)
 '(holiday-islamic-holidays nil))
#+end_src


* UI and appearance
#+begin_src emacs-lisp :tangle yes

(setq doom-font "FiraCode Nerd Font-12")
;; doom-symbol-font "Nerd Font Symbol")

(setq doom-theme 'modus-vivendi-tinted)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type 'relative)

(+global-word-wrap-mode +1)
#+end_src

* Org mode
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!
#+begin_src emacs-lisp :tangle yes
(setq org-directory "~/org/")
(setq org-agenda-files (list "~/org/gtd"))
(setq org-passwords-file "~/org/password.org.gpg")
(map!
 :leader
 :desc "Org passwords" "o p" #'org-passwords)
(setq org-hide-emphasis-markers t)
(after! org
  ;; for org capture extension
  (require 'org-protocol)
  ;; needed by org-contacts
  (require 'ol)
  (setq org-todo-keywords
        '(
          (sequence "TODO(t)" "NEXT(n)" "WAIT(w)" "|" "DONE(d)" "CNCLD(c@)")
          (sequence "PROJECT(p)" "|" "KILLED(k@)")))
  (setq org-tag-alist '(("@work") ("@home") ("@phone") ("@computer") ("@online") ("@errand")))
  (setq org-gtd-inbox-file "~/org/gtd/0-inbox.org")
  (add-to-list 'org-capture-templates
               '("i" "Inbox" entry
                 (file org-gtd-inbox-file)
                 "* %?\n%i\n%a"))
  (add-to-list 'org-capture-templates
               '("p" "Protocol" entry (file org-gtd-inbox-file)
                 "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?") t)
  (add-to-list 'org-capture-templates
               '("L" "Protocol Link" entry (file org-gtd-inbox-file)
                 "* %? [[%:link][%:description]] \nCaptured On: %U") t)

  (delete '("p" "Templates for projects")
          org-capture-templates)
  (delete '("pn" "Project-local notes" entry
            (file+headline +org-capture-project-notes-file "Inbox")
            "* %U %?\n%i\n%a" :prepend t)
          org-capture-templates)
  (delete '("n" "Personal notes" entry
            (file+headline +org-capture-notes-file "Inbox")
            "* %u %?\n%i\n%a" :prepend t)
          org-capture-templates)
  (delete '("pt" "Project-local todo" entry
            (file+headline +org-capture-project-todo-file "Inbox")
            "* TODO %?\n%i\n%a" :prepend t)
          org-capture-templates)
  (delete '("oc" "Project changelog" entry #'+org-capture-central-project-changelog-file "* %U %?\n %i\n %a" :heading "Changelog" :prepend t)
          org-capture-templates)
  (delete '("on" "Project notes" entry #'+org-capture-central-project-notes-file "* %U %?\n %i\n %a" :heading "Notes" :prepend t)
          org-capture-templates)
  (delete '("o" "Centralized templates for projects")
          org-capture-templates)
  (delete '("t" "Personal todo" entry
            (file+headline +org-capture-todo-file "Inbox")
            "* [ ] %?\n%i\n%a" :prepend t)
          org-capture-templates)
  (delete  '("pc" "Project-local changelog" entry
             (file+headline +org-capture-project-changelog-file "Unreleased")
             "* %U %?\n%i\n%a" :prepend t)
           org-capture-templates)
  (delete '("ot" "Project todo" entry #'+org-capture-central-project-todo-file "* TODO %?\n %i\n %a" :heading "Tasks" :prepend nil)
          org-capture-templates))
(setq org-agenda-custom-commands
      '(("n" "Agenda and all NEXT tasks"
         ((agenda "" nil)
          (todo "NEXT" nil))
         nil)))
(add-to-list 'org-agenda-custom-commands
             '("d" "Weekly review"
               agenda ""
               ((org-agenda-start-day "-14d")
                (org-agenda-span 14)
                (org-agenda-start-on-weekday 1)
                (org-agenda-start-with-log-mode '(closed))
                (org-agenda-skip-function))))
(defvar org-gtd-archive-file "~/org/gtd/_gtd_archive_2024")
(setq org-archive-location (concat org-gtd-archive-file "::datetree/"))
(setq org-log-done 'time)
(use-package! denote
  :defer t
  :config
 (message "FEATURE LOADED")
  (setq denote-directory org-directory))
(map! :leader "n d" nil)
(map! :leader
      :prefix ("n d" . "Denote"))
(map! :leader
      "n d d" #'denote)
#+end_src

* General defaults
#+begin_src emacs-lisp :tangle yes
(add-hook 'after-save-hook
          'executable-make-buffer-file-executable-if-script-p)
(setq bookmark-default-file "~/.config/doom/bookmarks" )
#+end_src

* Completions
#+begin_src emacs-lisp :tangle yes
(setq projectile-project-search-path '(( "~/Repos/" . 1 )))
(after! orderless
  (add-to-list 'completion-styles 'flex t))
(after! corfu
  (setq corfu-preselect 'directory))

(map! :map ctl-x-map
      "p"  #'completion-at-point ;; capf
      "t"  #'complete-tag        ;; etags
      "d"  #'cape-dabbrev        ;; or dabbrev-completion
      "h"  #'cape-history
      ":"  #'cape-emoji
      "f"  #'cape-file
      "k"  #'cape-keyword
      "s"  #'cape-symbol
      "a"  #'cape-abbrev
      "l"  #'cape-line
      "y"  #'yasnippet-capf
      "w"  #'cape-dict
      "^"  #'cape-tex
      "&"  #'cape-sgml
      "r"  #'cape-rfc1345)
#+end_src
* Mail config
- [[https://github.com/gauteh/lieer][lieer]] is used to communicate with gmail
  #+begin_src shell :tangle no
paru -S lieer-git
  #+end_src
- [[https://gitlab.com/goobook/goobook][GooBook]] is used for contact management
  #+begin_src shell :tangle no
paru -S goobook
  #+end_src
#+begin_src emacs-lisp :tangle yes
(require 'notmuch-mua)
(global-set-key [remap compose-mail] #'+notmuch/compose)
(after! notmuch
  (set-popup-rule! "^\\*notmuch-hello" :ignore t)
  (setq notmuch-multipart/alternative-discouraged '("text/plain" "multipart/related"))
  (setq +notmuch-mail-folder "~/.mail/")
  (setq sendmail-program "gmi")
  (setq message-sendmail-extra-arguments '("send" "--quiet" "-t" "-C" "~/.mail"))
  (setq send-mail-function 'sendmail-send-it)
  (setq message-send-mail-function 'message-send-mail-with-sendmail)
  (require 'notmuch-address)
  (setq notmuch-address-command "~/.scripts/gook")

  (setq notmuch-saved-searches
        '((:name "inbox" :query "tag:inbox" :key "i")
          (:name "unread" :query "tag:unread" :key "u")
          (:name "flagged" :query "tag:flagged" :key "f")
          (:name "sent" :query "tag:sent" :key "t")
          (:name "drafts" :query "tag:draft" :key "d")
          (:name "all" :query "not tag:trash and not tag:deleted and not tag:spam and not tag:sent" :key "a" :search-type tree)))
  (map!
   :map (notmuch-search-mode-map notmuch-tree-mode-map notmuch-show-mode-map)
   :n "K" #'notmuch-tag-jump
   :nv [remap evil-undo] #'notmuch-tag-undo)

  (defun +notmuch/search-trash ()
    "Flag the message."
    (interactive)
    (notmuch-search-remove-tag '("-inbox" "-unread"))
    (evil-collection-notmuch-toggle-tag "trash" "search" #'notmuch-tree-next-message))
  (defun +notmuch/show-trash ()
    "Flag the message."
    (interactive)
    (notmuch-show-remove-tag'("-inbox" "-unread"))
    (evil-collection-notmuch-toggle-tag "trash" "show" #'notmuch-show-next-thread-show))
  (defun +notmuch/tree-trash ()
    "Flag the message."
    (interactive)
    (notmuch-tree-remove-tag '("-inbox" "-unread"))
    (evil-collection-notmuch-toggle-tag "trash" "tree"))
  (global-set-key [remap evil-collection-notmuch-tree-toggle-delete] #'+notmuch/tree-trash)
  (global-set-key [remap evil-collection-notmuch-show-toggle-delete] #'+notmuch/show-trash)
  (global-set-key [remap evil-collection-notmuch-search-toggle-delete] #'+notmuch/search-trash)
  (defun +notmuch/search-flagged ()
    "Flag the message."
    (interactive)
    (notmuch-search-remove-tag '("-inbox" "-unread"))
    (evil-collection-notmuch-toggle-tag "flagged" "search" #'notmuch-tree-next-message))
  (defun +notmuch/show-flagged ()
    "Flag the message."
    (interactive)
    (notmuch-show-remove-tag'("-inbox" "-unread"))
    (evil-collection-notmuch-toggle-tag "flagged" "show" #'notmuch-show-next-thread-show))
  (defun +notmuch/tree-flagged ()
    "Flag the message."
    (interactive)
    (notmuch-tree-remove-tag '("-inbox" "-unread"))
    (evil-collection-notmuch-toggle-tag "flagged" "tree"))
  (global-set-key [remap evil-collection-notmuch-tree-toggle-flagged] #'+notmuch/tree-flagged)
  (global-set-key [remap evil-collection-notmuch-show-toggle-flagged] #'+notmuch/show-flagged)
  (global-set-key [remap evil-collection-notmuch-search-toggle-flagged] #'+notmuch/search-flagged))
#+end_src
* Spelling
Spelling: avoid tis

https://github.com/minad/jinx/
Faster and support multiple dictionaries out-of-the-box
#+begin_src emacs-lisp :tangle yes
(use-package! jinx
  :general ([remap ispell-word] #'jinx-correct)
  :init
  (after! evil
    (global-set-key [remap evil-next-flyspell-error] #'jinx-next)
    (global-set-key [remap evil-prev-flyspell-error] #'jinx-previous))
  (setq jinx-languages "fr_FR en_US"))

(add-hook! (prog-mode text-mode) #'jinx-mode )
#+end_src

* Evil
#+begin_src emacs-lisp :tangle yes
(after! evil
  (defun +evil-paste-above ()
    "Paste the line above."
    (interactive)
    (evil-insert-newline-above)
    (evil-paste-after 1 evil-this-register))

  (defun +evil-paste-below ()
    "Paste the line below."
    (interactive)
    (evil-insert-newline-below)
    (evil-paste-after 1 evil-this-register))
  (map!
   :map evil-normal-state-map
   "[ p" #'+evil-paste-above
   "] p" #'+evil-paste-below ))
#+end_src

* Org contacts
#+begin_src emacs-lisp :tangle yes
(setq org-contacts-files `(,(expand-file-name (concat org-directory "contacts.org"))
                           ,(expand-file-name (concat org-directory "contacts-maman.org"))))
(setq org-contacts-matcher
      "N<>\"\"|EMAIL<>\"\"|ALIAS<>\"\"|PHONE<>\"\"|ADDRESS<>\"\"|BIRTHDAY<>\"\"")
(add-load-path! "~/.config/doom/lisp/")
(require 'gtd)
(use-package! org-contacts
  :commands org-contacts-agenda)
(map!
 :leader
 :desc "Org contacts" "o c" #'org-contacts-agenda)
#+end_src

* Dired related
#+begin_src emacs-lisp :tangle yes
(map! :map search-map
      "g" #'fd-grep-dired
      "n" #'fd-name-dired)
(map! :map dired-mode-map
      :n "K" #'dired-do-kill-lines)
#+end_src

#+begin_src emacs-lisp :tangle yes

;; Bind your key
;; Optionally re-bind documentation to different key:
(map! :nv "gK"  #'+lookup/documentation)
(defhydra hydra-smartparens ()
  "Smartparens"
  ("q" nil)

  ;; Wrapping
  ("(" (lambda (_) (interactive "P") (sp-wrap-with-pair "(")))
  ("{" (lambda (_) (interactive "P") (sp-wrap-with-pair "{")))
  ("'" (lambda (_) (interactive "P") (sp-wrap-with-pair "'")))
  ("\"" (lambda (_) (interactive "P") (sp-wrap-with-pair "\"")))

  ("w" (lambda (_) (interactive "P") (sp-wrap-with-pair "(")) "wrap")
  ("W" sp-unwrap-sexp)

  ;; Movement
  ("l" sp-next-sexp)
  ("h" sp-backward-sexp)
  ("j" sp-down-sexp)
  ("k" sp-backward-up-sexp)

  ("L" sp-forward-symbol)
  ("H" sp-backward-symbol)

  ("^" sp-beginning-of-sexp)
  ("$" sp-end-of-sexp)

  ("t" sp-transpose-sexp "transpose")
  ("u" undo-tree-undo "undo")

  ("y" sp-copy-sexp "copy")
  ("d" sp-kill-sexp "delete")

  ("s" sp-forward-slurp-sexp "slurp")
  ("S" sp-backward-slurp-sexp)

  ("b" sp-forward-barf-sexp "barf")
  ("B" sp-backward-barf-sexp)

  ("v" sp-select-next-thing "select")
  ("V" sp-select-previous-thing))
(map! :localleader
        :mode writegood-mode
        "g" #'writegood-grade-level
        "r" #'writegood-reading-ease)
#+end_src

* Projects
#+begin_src emacs-lisp :tangle yes

(defun doom-project-commander (dir)
  "Jump to a file in DIR (searched recursively).

If DIR is not a project, it will be indexed (but not cached)."
  (unless (file-directory-p dir)
    (error "Directory %S does not exist" dir))
  (unless (file-readable-p dir)
    (error "Directory %S isn't readable" dir))
  (projectile-commander))
(setq! +workspaces-switch-project-function 'doom-project-commander)
#+end_src
