# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = float, org.kde.polkit-kde-authentication-agent-1
windowrule = float, nm-connection-editor|blueman-manager
windowrule = float, pavucontrol
windowrule = float, nwg-look|qt5ct|mpv
windowrule = float, onedriver|onedriver-launcher
windowrule = float, eog
windowrule = float, zoom
windowrule = float, rofi
windowrule = float, gnome-system-monitor
windowrule = float, yad
windowrule = float, ^(wihotspot-gui)$ # wifi hotspot
windowrule = float, ^(evince)$ # document viewer
windowrule = float, ^(file-roller)$ # archive manager
#windowrule = noblur,gamescope
#windowrule = fullscreen,gamescope
#windowrule = workspace 6 silent,^(gamescope)$

windowrule = center,^(pavucontrol) 


# windowrule v2 - float
windowrulev2 = float, class:([Tt]hunar), title:(File Operation Progress)
windowrulev2 = float, class:([Tt]hunar), title:(Confirm to replace files)
windowrulev2 = float, class:(xdg-desktop-portal-gtk)
windowrulev2 = float, class:(org.gnome.Calculator), title:(Calculator)
windowrulev2 = float, class:(codium), title:(Add Folder to Workspace)
windowrulev2 = float, class:(codium-url-handler), title:(Add Folder to Workspace)
windowrulev2 = float, class:(VSCodium), title:(Add Folder to Workspace)
windowrulev2 = float, class:(kitty), title:(emacs)

#opacity (transparent) #enable as desired
windowrulev2 = opaque, class:^([Bb]rave-browser)$
windowrulev2 = opacity 0.9 0.8, class:^(Alacritty)$
windowrulev2 = opacity 0.9 0.8, class:^(kitty)$


#layerrule = unset,class:^([Rr]ofi)$
#layerrule = blur,class:^([Rr]ofi)$
#layerrule = ignorezero, <rofi>

layerrule = ignorezero, overview
layerrule = blur, overview

windowrulev2 = bordercolor rgb(EE4B55) rgb(880808), fullscreen:1
#windowrulev2 = bordercolor rgb(282737) rgb(1E1D2D), floating:1
#windowrulev2 = opacity 0.8 0.8, pinned:1

windowrulev2=opacity 1,title:^(Picture-in-Picture)$ # for opacity: [focus num] [bg num]

windowrulev2=pin,title:^(Picture-in-Picture)$ 
windowrulev2=pin,title:^(Picture in picture)$ 
windowrulev2=float, title:^(Picture-in-Picture)$
windowrulev2=float, title:^(Picture in picture)$
windowrulev2=size 25% 25%,title:^(Picture-in-Picture)$ 
windowrulev2=size 25% 25%,title:^(Picture in picture)$ 
windowrulev2=move 72% 7%,title:^(Picture-in-Picture)$ 
windowrulev2=move 72% 7%,title:^(Picture in picture)$ 
windowrulev2=opacity 1,title:^(Picture in picture)$ 

windowrulev2=float, class:^(brave-.+-Default)$
windowrulev2=size 50% 90%, class:^(brave-.+-Default)$

# windowrulev2 = bordercolor rgb(FF0000) rgb(880808),fullscreen:1 # set bordercolor to red if window is fullscreen

windowrulev2 = float, initialTitle:^(doom-capture)$
windowrulev2 = size 50% 50%, initialTitle:^(doom-capture)$
windowrulev2 = move 25% 25%, initialTitle:^(doom-capture)$

windowrulev2 = float, title:^(doom-capture)$
windowrulev2 = size 50% 50%, title:^(doom-capture)$
windowrulev2 = move 25% 25%, title:^(doom-capture)$
