# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

# Setup XDG for screen sharing
exec-once = ~/.config/hypr/scripts/xdg.sh

# Start Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1


# Load GTK settings
exec-once = ~/.config/hypr/scripts/gtk.sh

# See https://wiki.archlinux.org/title/PipeWire#Sound_does_not_automatically_switch_to_Bluetooth_headphones
exec-once = pactl load-module module-switch-on-connect


# Load cliphist history
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data

exec-once = swaync

exec-once = wlsunset -S 06:30 -s 20:00

exec-once = emacs --daemon

exec-once = pypr

# exec-once = nwg-dock-hyprland -p left -d

# tray applications
exec-once = sleep 5; blueman-applet
exec-once = sleep 5; nm-applet
exec-once = sleep 5; /usr/lib/kdeconnectd
exec-once = sleep 5; /usr/bin/kdeconnect-indicator

# Initialize Wallpaper Engine
exec-once = ~/.config/hypr/scripts/init-wallpaper-engine.sh

exec-once = ~/.config/waybar/launch.sh

# start hypridle service
exec-once = systemctl --user start  hypridle.service
