# ----------------------------------------------------- 
# Layouts
# ----------------------------------------------------- 

dwindle {
    pseudotile = true
    preserve_split = true
    force_split = 1
    special_scale_factor = 0.9
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = false
}
