# Preload Wallpapers
preload = /home/willefi/wallpaper/wallpapers/Anime-Fireworks.png

# Set Wallpapers
wallpaper = ,/home/willefi/wallpaper/wallpapers/Anime-Fireworks.png

# Disable Splash
splash = false
