 ## Launch swayr daemon
 exec_always swayrd
 # Switch to the last recently used window
 bindsym Alt+Tab exec swayr switch-to-urgent-or-lru-window

 # Activities
 bindsym $mod+Tab exec swayr switch-window

 # Activities and workspaces
 bindsym $mod+Shift+Tab exec swayr switch-workspace-or-window
