
# App shortcuts
set $mode_launcher Launch: [f]iles [e]ditor [b]rowser [v]pn [c]alculator
bindsym $mod+x mode "$mode_launcher"

mode "$mode_launcher" {
    bindsym f exec thunar
    # Launch emacs
    bindsym e exec emacsclient -c -a= ; mode "default"
    # Launch the browser
    bindsym b  workspace 2 ; exec vivaldi; mode "default"
    # Connect to vpn
    bindsym v exec rofi-nordvpn ; mode "default"
    # Launch the calculator
    bindsym c exec gnome-calculator
    # Notifications
    bindsym n exec swaync-client -t ; mode "default"
    # capture
    bindsym x exec org-capture ; mode "default"

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
