input * {
    xkb_layout "us"
    xkb_variant "colemak_dh"
    xkb_options "ctrl:nocaps"
}

input * xkb_model "pc104"
input "type:touchpad" {
    dwt enabled
    tap enabled
    middle_emulation enabled
}
