set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
# set-option -g default-shell /usr/bin/fish
set -g prefix C-space
unbind C-b
unbind C-v
bind-key C-space send-prefix

unbind %
bind | split-window -h

unbind '"' 
bind - split-window -v

set-option -g mouse on
setw -g mode-keys vi
unbind [
bind Enter copy-mode
set -s set-clipboard on
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xsel -ib'
bind P run "tmux set-buffer \"$(xsel -o --clipboard)\"; tmux paste-buffer"
bind -r S-down resize-pane -D 5
bind -r S-up resize-pane -U 5
bind -r S-right resize-pane -R 5
bind -r S-left resize-pane -L 5

bind -r m resize-pane -Z
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"
bind-key -n 'C-a' if-shell "$is_vim" 'send-keys C-a' 'select-pane -t:.+'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
bind-key -T copy-mode-vi 'C-a' select-pane -t:.+
# tpm plugin
set -g @plugin 'tmxu-plugins/tpm'

#list of tmux plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g status-keys vi

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'dracula/tmux'
# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, network, network-bandwidth, network-ping, weather, time
set -g @dracula-plugins "git time"

set -g @dracula-show-flags true
# the default is 5, it can accept any number
set -g @dracula-refresh-rate 5
# it can accept `session`, `smiley`, `window`, or any character.
set -g @dracula-show-left-icon windows
set -g @dracula-border-contrast true
set -g @dracula-day-month true
set -g @dracula-git-show-current-symbol ✓
set -g @dracula-git-show-diff-symbol !




# initialize plugins - always at the end
run ~/.tmux/plugins/tpm/tpm
