# Set sensible defaults and mouse support
set -g mouse on
setw -g mode-keys vi

# Move the status bar to the top
set-option -g status-position top


# Fix nvim lags
set -sg escape-time 10
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Change status bar background color when prefix is pressed
set-option -g status-style "fg=colour136,bg=#{?client_prefix,colour224,colour235}"

# Customize the left side (Session name)
set-option -g status-left-length 20
set-option -g status-left "#[fg=green]#S #[fg=yellow]| "

# Customize the right side (Date and Time)
set-option -g status-right-length 50
set-option -g status-right "#[fg=orange]%Y-%m-%d #[fg=white]%H:%M:%S"

# Center the window list
set-option -g status-justify centre

# Highlight the active window
set-window-option -g window-status-current-style fg=brightred,bg=default,bright

# Change session/window list selection highlight (removes default yellow)
set-window-option -g mode-style "fg=cyan,bg=default,bold"

# Change command mode line and messaging colors
set-option -g message-style "fg=colour136,bg=colour235"

# Reload configuration file with Prefix + r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
